name: Compila per Amiga

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Questa immagine è pubblica e testata
    container: walkero/amiga-gcc:latest

    steps:
    - name: Scarica il codice
      uses: actions/checkout@v4

    - name: Compila il gioco
      # Aggiungo -s per rimuovere i simboli di debug (rende il file più piccolo)
      run: m68k-amigaos-gcc main.c -o engine.exe -noixemul -Os -s

    - name: Salva l'eseguibile
      uses: actions/upload-artifact@v4
      with:
        name: MioGiocoAmiga
        path: engine.exe
