name: Compila per Amiga

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # CORREZIONE DEFINITIVA: Usiamo il registro ufficiale di GitHub
    container: ghcr.io/bebbo/amiga-gcc:latest

    steps:
    - name: Scarica il codice
      uses: actions/checkout@v4

    - name: Compila il gioco
      # Compiliamo!
      run: m68k-amigaos-gcc main.c -o engine.exe -noixemul -Os

    - name: Salva l'eseguibile
      uses: actions/upload-artifact@v4
      with:
        name: MioGiocoAmiga
        path: engine.exe
